import { z } from "zod";

const envSchema = z.object({
  NEXT_PUBLIC_APP_URL: z.string().url().default("http://localhost:3000"),
  NEXT_PUBLIC_APP_NAME: z.string().min(1).default("RAG Knowledge Assistant"),
  NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: z.string().min(1).optional(),
  NEXT_PUBLIC_SENTRY_DSN: z.string().url().optional(),
  NEXT_PUBLIC_POSTHOG_KEY: z.string().min(1).optional(),
  NEXT_PUBLIC_POSTHOG_HOST: z.string().url().default("https://us.i.posthog.com"),
  CLERK_SECRET_KEY: z.string().min(1).optional(),
  DATABASE_URL: z.string().url().optional(),
  SENTRY_DSN: z.string().url().optional(),
  SENTRY_ENVIRONMENT: z.string().min(1).default("development"),
  POSTHOG_KEY: z.string().min(1).optional(),
  POSTHOG_HOST: z.string().url().default("https://us.i.posthog.com"),
  LANGSMITH_TRACING: z.coerce.boolean().default(false),
  LANGSMITH_API_KEY: z.string().min(1).optional(),
  LANGSMITH_PROJECT: z.string().min(1).default("rag-knowledge-assistant"),
  OPENAI_API_KEY: z.string().min(1).optional(),
  ANTHROPIC_API_KEY: z.string().min(1).optional(),
  GOOGLE_API_KEY: z.string().min(1).optional(),
  EMBEDDING_PROVIDER: z.string().min(1).default("openai"),
  EMBEDDING_MODEL: z.string().min(1).default("text-embedding-3-small"),
  EMBEDDING_DIMENSIONS: z.coerce.number().int().positive().default(1536),
  EMBEDDING_BATCH_SIZE: z.coerce.number().int().positive().max(2048).default(64),
  CHUNK_SIZE: z.coerce.number().int().positive().default(1000),
  CHUNK_OVERLAP: z.coerce.number().int().min(0).default(200),
  OPENAI_CHAT_MODEL: z.string().min(1).default("gpt-4.1"),
  ANTHROPIC_CHAT_MODEL: z.string().min(1).default("claude-sonnet-4-5-20250929"),
  GEMINI_CHAT_MODEL: z.string().min(1).default("gemini-2.5-flash"),
  AI_PRIMARY_PROVIDER: z.enum(["openai", "anthropic", "gemini"]).default("openai"),
  AI_ROUTING_STRATEGY: z.enum(["balanced", "cost", "latency", "quality"]).default("balanced"),
  AI_FALLBACK_ORDER: z.string().min(1).default("openai,anthropic,gemini"),
  AI_REQUEST_TIMEOUT_MS: z.coerce.number().int().positive().default(45000),
  AGENT_MAX_STEPS: z.coerce.number().int().positive().max(12).default(6),
  WEB_SEARCH_ENDPOINT: z.string().url().default("https://api.duckduckgo.com/"),
  ENCRYPTION_KEY: z.string().min(32).optional(),
  RATE_LIMIT_WINDOW_SECONDS: z.coerce.number().int().positive().default(60),
  RATE_LIMIT_REQUESTS: z.coerce.number().int().positive().default(60),
  AI_RATE_LIMIT_REQUESTS: z.coerce.number().int().positive().default(20),
  SECURITY_BLOCK_PROMPT_INJECTION: z.coerce.boolean().default(true),
  SECURITY_ENABLE_MODERATION: z.coerce.boolean().default(true),
  DATA_RETENTION_DAYS: z.coerce.number().int().positive().default(365),
  CONNECTOR_WEBHOOK_SECRET: z.string().min(16).optional(),
  RAG_RETRIEVAL_LIMIT: z.coerce.number().int().positive().max(50).default(8),
  RAG_MIN_SIMILARITY: z.coerce.number().min(0).max(1).default(0.2),
  RAG_MULTI_QUERY_LIMIT: z.coerce.number().int().positive().max(6).default(4),
  RAG_CANDIDATE_MULTIPLIER: z.coerce.number().int().positive().max(8).default(4),
  RAG_CONTEXT_MAX_TOKENS: z.coerce.number().int().positive().default(3200),
  RAG_RETRIEVAL_CACHE_SECONDS: z.coerce.number().int().min(0).default(60),
  AI_MAX_OUTPUT_TOKENS: z.coerce.number().int().positive().default(1600),
  ANALYTICS_CACHE_SECONDS: z.coerce.number().int().min(0).default(30),
  MEMORY_RECENT_MESSAGE_LIMIT: z.coerce.number().int().positive().max(50).default(10),
  MEMORY_RETRIEVAL_LIMIT: z.coerce.number().int().positive().max(20).default(6),
  MEMORY_MAX_CONTEXT_TOKENS: z.coerce.number().int().positive().default(1800),
  MEMORY_SUMMARY_TRIGGER_TOKENS: z.coerce.number().int().positive().default(2400),
});

export const env = envSchema.parse({
  NEXT_PUBLIC_APP_URL: process.env.NEXT_PUBLIC_APP_URL,
  NEXT_PUBLIC_APP_NAME: process.env.NEXT_PUBLIC_APP_NAME,
  NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY,
  NEXT_PUBLIC_SENTRY_DSN: process.env.NEXT_PUBLIC_SENTRY_DSN,
  NEXT_PUBLIC_POSTHOG_KEY: process.env.NEXT_PUBLIC_POSTHOG_KEY,
  NEXT_PUBLIC_POSTHOG_HOST: process.env.NEXT_PUBLIC_POSTHOG_HOST,
  CLERK_SECRET_KEY: process.env.CLERK_SECRET_KEY,
  DATABASE_URL: process.env.DATABASE_URL,
  SENTRY_DSN: process.env.SENTRY_DSN ?? process.env.NEXT_PUBLIC_SENTRY_DSN,
  SENTRY_ENVIRONMENT: process.env.SENTRY_ENVIRONMENT ?? process.env.NODE_ENV,
  POSTHOG_KEY: process.env.POSTHOG_KEY ?? process.env.NEXT_PUBLIC_POSTHOG_KEY,
  POSTHOG_HOST: process.env.POSTHOG_HOST ?? process.env.NEXT_PUBLIC_POSTHOG_HOST,
  LANGSMITH_TRACING: process.env.LANGSMITH_TRACING,
  LANGSMITH_API_KEY: process.env.LANGSMITH_API_KEY,
  LANGSMITH_PROJECT: process.env.LANGSMITH_PROJECT,
  OPENAI_API_KEY: process.env.OPENAI_API_KEY,
  ANTHROPIC_API_KEY: process.env.ANTHROPIC_API_KEY,
  GOOGLE_API_KEY: process.env.GOOGLE_API_KEY ?? process.env.GEMINI_API_KEY,
  EMBEDDING_PROVIDER: process.env.EMBEDDING_PROVIDER,
  EMBEDDING_MODEL: process.env.EMBEDDING_MODEL,
  EMBEDDING_DIMENSIONS: process.env.EMBEDDING_DIMENSIONS,
  EMBEDDING_BATCH_SIZE: process.env.EMBEDDING_BATCH_SIZE,
  CHUNK_SIZE: process.env.CHUNK_SIZE,
  CHUNK_OVERLAP: process.env.CHUNK_OVERLAP,
  OPENAI_CHAT_MODEL: process.env.OPENAI_CHAT_MODEL,
  ANTHROPIC_CHAT_MODEL: process.env.ANTHROPIC_CHAT_MODEL,
  GEMINI_CHAT_MODEL: process.env.GEMINI_CHAT_MODEL,
  AI_PRIMARY_PROVIDER: process.env.AI_PRIMARY_PROVIDER,
  AI_ROUTING_STRATEGY: process.env.AI_ROUTING_STRATEGY,
  AI_FALLBACK_ORDER: process.env.AI_FALLBACK_ORDER,
  AI_REQUEST_TIMEOUT_MS: process.env.AI_REQUEST_TIMEOUT_MS,
  AGENT_MAX_STEPS: process.env.AGENT_MAX_STEPS,
  WEB_SEARCH_ENDPOINT: process.env.WEB_SEARCH_ENDPOINT,
  ENCRYPTION_KEY: process.env.ENCRYPTION_KEY,
  RATE_LIMIT_WINDOW_SECONDS: process.env.RATE_LIMIT_WINDOW_SECONDS,
  RATE_LIMIT_REQUESTS: process.env.RATE_LIMIT_REQUESTS,
  AI_RATE_LIMIT_REQUESTS: process.env.AI_RATE_LIMIT_REQUESTS,
  SECURITY_BLOCK_PROMPT_INJECTION: process.env.SECURITY_BLOCK_PROMPT_INJECTION,
  SECURITY_ENABLE_MODERATION: process.env.SECURITY_ENABLE_MODERATION,
  DATA_RETENTION_DAYS: process.env.DATA_RETENTION_DAYS,
  CONNECTOR_WEBHOOK_SECRET: process.env.CONNECTOR_WEBHOOK_SECRET,
  RAG_RETRIEVAL_LIMIT: process.env.RAG_RETRIEVAL_LIMIT,
  RAG_MIN_SIMILARITY: process.env.RAG_MIN_SIMILARITY,
  RAG_MULTI_QUERY_LIMIT: process.env.RAG_MULTI_QUERY_LIMIT,
  RAG_CANDIDATE_MULTIPLIER: process.env.RAG_CANDIDATE_MULTIPLIER,
  RAG_CONTEXT_MAX_TOKENS: process.env.RAG_CONTEXT_MAX_TOKENS,
  RAG_RETRIEVAL_CACHE_SECONDS: process.env.RAG_RETRIEVAL_CACHE_SECONDS,
  AI_MAX_OUTPUT_TOKENS: process.env.AI_MAX_OUTPUT_TOKENS,
  ANALYTICS_CACHE_SECONDS: process.env.ANALYTICS_CACHE_SECONDS,
  MEMORY_RECENT_MESSAGE_LIMIT: process.env.MEMORY_RECENT_MESSAGE_LIMIT,
  MEMORY_RETRIEVAL_LIMIT: process.env.MEMORY_RETRIEVAL_LIMIT,
  MEMORY_MAX_CONTEXT_TOKENS: process.env.MEMORY_MAX_CONTEXT_TOKENS,
  MEMORY_SUMMARY_TRIGGER_TOKENS: process.env.MEMORY_SUMMARY_TRIGGER_TOKENS,
});
